# Generated by Django 5.0.7 on 2024-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revisione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numRevisione', models.CharField(max_length=100)),
                ('numTarga', models.CharField(max_length=100)),
                ('dataRevisione', models.DateField()),
                ('esito', models.CharField(max_length=100)),
                ('motivazione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Targa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_targa', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
